# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathexpression',
            name='step',
            field=models.DecimalField(decimal_places=6, default=0.1, max_digits=10),
        ),
    ]
